"""Add or update models

Revision ID: fe272d4790cd
Revises: c390de4c0fc7
Create Date: 2025-12-29 23:57:39.189606

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fe272d4790cd'
down_revision = 'c390de4c0fc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback_test', sa.Text(), nullable=False))
        batch_op.drop_column('feedback_text')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('feedback_text', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('feedback_test')

    # ### end Alembic commands ###
